export const COUNTRY_METHODS = {
  CI: ["OMCIV2", "MOMOCI", "FLOOZ", "WAVECI"],
  BF: ["PAWAPAY"],
  ML: ["OMML"],
  NE: ["AIRTELNG"],
  GW: ["OMGN"],
  CM: ["PAWAPAY"],
  BJ: ["PAWAPAY"],
  CD: ["PAWAPAY"],
  GA: ["PAWAPAY"],
  GH: ["PAWAPAY"],
  KE: ["PAWAPAY"],
  MW: ["PAWAPAY"],
  NG: ["PAWAPAY"],
  CG: ["PAWAPAY"],
  RW: ["PAWAPAY"],
  SN: ["PAWAPAY"],
  SL: ["PAWAPAY"],
  TZ: ["PAWAPAY"],
  UG: ["PAWAPAY"],
  ZM: ["PAWAPAY"],
};

export const METHOD_LABELS = {
  PAWAPAY: "Mobile Money",
  OMCIV2: "Orange Money",
  MOMOCI: "MTN",
  FLOOZ: "Moov",
  WAVECI: "Wave",
  OMML: "Orange Money",
  AIRTELNG: "Airtel Money",
  OMGN: "Orange Money",
};
